cohorts:
  glioma:
    defaults:
      learning_rate: 0.0001
      batch_size: 2
      aggregation_epochs: 1
      weight_decay: 0.00001
      fedproxloss_mu: 0.0
      cache_dataset: 1.0
    sites:
      site-1: {}
      site-2:
        learning_rate: 0.00008
